name: LAMP Project CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  code-validation:
    name: Code Validation
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check PHP syntax
      run: |
        sudo apt-get update
        sudo apt-get install -y php-cli
        find . -name "*.php" -exec php -l {} \;
    
    - name: Check js syntax
      run: |
        if [ -f script.js ]; then
          sudo npm install -g jshint
          echo '{"esversion": 6}' > .jshintrc
          jshint script.js
        fi

  file-structure:
    name: File Structure Check
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Verify project files
      run: |
        test -f index.php
        test -f contact.php
        test -f db.php
        test -f style.css
        test -f script.js
        
    - name: Check scripts directory
      run: |
        test -d scripts/
        test -f scripts/backup.sh
        test -f scripts/lamp.sh
        test -x scripts/backup.sh
        test -x scripts/lamp.sh

  basic-tests:
    name: Basic Tests
    runs-on: ubuntu-latest
    needs: [code-validation, file-structure]
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: testpassword
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      run: |
        sudo apt-get update
        sudo apt-get install -y php-cli php-mysql
    
    - name: Test PHP functionality
      run: |
        php -r "echo 'PHP version: ' . phpversion() . PHP_EOL;"
        php -r "echo 'MySQL extension: ' . (extension_loaded('mysqli') ? 'OK' : 'Missing') . PHP_EOL;"
    
    - name: Test MySQL connection
      run: |
        php -r "
        try {
            \$mysqli = new mysqli('127.0.0.1', 'root', 'testpassword', 'test_db');
            echo 'MySQL connection: OK' . PHP_EOL;
        } catch(Exception \$e) {
            echo 'MySQL connection failed: ' . \$e->getMessage() . PHP_EOL;
            exit(1);
        }
        "

  summary:
    name: Build Summary
    runs-on: ubuntu-latest
    needs: [code-validation, file-structure, basic-tests]
    if: always()
    
    steps:
    - name: Show results
      run: |
        echo "=== BUILD SUMMARY ==="
        echo "Code Validation: ${{ needs.code-validation.result }}"
        echo "File Structure: ${{ needs.file-structure.result }}"
        echo "Basic Tests: ${{ needs.basic-tests.result }}"
        echo "====================="
        
        if [ "${{ needs.code-validation.result }}" == "success" ] && [ "${{ needs.file-structure.result }}" == "success" ] && [ "${{ needs.basic-tests.result }}" == "success" ]; then
          echo "All checks passed!"
        else
          echo "Some checks failed - review the logs above"
        fi
